const WORKSITE_REP_MAP = {
  "37th Street Bakery formerly GOLD STANDARD — Chicago, IL": "msalgado@cmrjb.org",
  "5 Star Hotel Laundry - PureStar Group - Loews Hotel — Rosemont, IL": "dnava@cmrjb.org",
  "5 Star Hotel Laundry - PureStar Group — Chicago, IL": "dnava@cmrjb.org",
  "A. G. Simpson (USA), Inc. — Sterling Heights, MI": "cmartin@cmrjb.org",
  "Accurate Felt & Gasket — Cicero, IL": "msalgado@cmrjb.org",
  "Aladdin @ Purdue Northwest University — Hammond, IN": "jortiz@cmrjb.org",
  "Aladdin Food Services @ Shawnee State University — Portsmouth, OH": "jtyler@cmrjb.org",
  "Alpha & Omega Building Serv. (U. Dayton) — Dayton, OH": "jtyler@cmrjb.org",
  "ALSCO  Inc. — Wauwatosa, WI": "jolson@cmrjb.org",
  "ALSCO - Denver Linen — Denver, CO": "msalgado@cmrjb.org",
  "Alsco American Linen — Salt Lake City, UT": "msalgado@cmrjb.org",
  "ALSCO Inc. — Grand Junction, CO": "msalgado@cmrjb.org",
  "ALSCO Linen — Chicago, IL": "dnava@cmrjb.org",
  "Alsco Uniforms — St. Louis, MO": "emoore@cmrjb.org",
  "Amalgamated Bank of Chicago — Chicago, IL": "adiaz@cmrjb.org",
  "AMCOR — Terre Haute, IN": "cmartin@cmrjb.org",
  "American Family Field dba Miller Park (1) Concessions — Milwaukee, WI": "ptorres@cmrjb.org",
  "American Water Co. (Illinois) Peoria Dist. — Peoria, IL": "mbaeza@cmrjb.org",
  "Aramark @ Bradley University — Peoria, IL": "mbaeza@cmrjb.org",
  "Aramark @ Capian — Caspian, MI": "echavez@cmrjb.org",
  "Aramark @ Cleveland State — Cleveland, OH": "kgillis@cmrjb.org",
  "Aramark @ Ford Ohio Truck Plant Avon — Avon Lake, OH": "rwilson@cmrjb.org",
  "Aramark @ Ford Sharonville Cafeteria, Unit # 0419 — Sharonsville, OH": "jtyler@cmrjb.org",
  "Aramark @ Heritage Bank Center — Cincinnati, OH": "jtyler@cmrjb.org",
  "Aramark @ Huntington Fields (Non-Premium) — Cleveland, OH": "rwilson@cmrjb.org",
  "Aramark @ Huntington Fields (Premium) — Cleveland, OH": "rwilson@cmrjb.org",
  "Aramark @ Lucas County Jail — Toledo, OH": "doug.warren@cmrjb.org",
  "Aramark @ Rocket Mortgage Field House — Cleveland, OH": "rwilson@cmrjb.org",
  "Aramark @ Rockwell Collins Manufacturing — Cedar Rapids, IA": "aszoke@cmrjb.org",
  "Aramark @ University of  Cincinnati (CenterCourt) — Cincinnati, OH": "jtyler@cmrjb.org",
  "Aramark @ University of  Cincinnati (Retail Operations) — Cincinnati, OH": "jtyler@cmrjb.org",
  "Aramark Tri-C — Cleveland, OH": "rwilson@cmrjb.org",
  "Aramark Uniform, Wixom Plant - MC 574 — Wixom, MI": "rburks@cmrjb.org",
  "ASM  - Global (SeaGate Convention Centre) — Toledo, OH": "cmartin@cmrjb.org",
  "Auria — Fremont, OH": "cmartin@cmrjb.org",
  "Aurora Textile Finishing Co. — Yorkville, IL": "mbaeza@cmrjb.org",
  "AVI @ BP Husky Refining — Oregon, OH": "doug.warren@cmrjb.org",
  "AVI @ Huntington Center — Toledo, OH": "cmartin@cmrjb.org",
  "AVI @ Kenyon College — Warren, OH": "kgillis@cmrjb.org",
  "AVI Foodsystems Inc. dba Huntington and Glass City Center — Toledo, OH": "cmartin@cmrjb.org",
  "AVI Foodsystems Inc., Toledo Branch [Warehouse] — Maumee, OH": "doug.warren@cmrjb.org",
  "Avia of Kenosha — Kenosha, WI": "jolson@cmrjb.org",
  "Biofit Engineered Products — Bowling Green, OH": "doug.warren@cmrjb.org",
  "Brooks Brothers — Chicago, IL": "mbaeza@cmrjb.org",
  "BYP100 Education Fund — Springfield, IL": "mfrost@cmrjb.org",
  "C-Line Products, Inc. — Mt. Prospect, IL": "msalgado@cmrjb.org",
  "Cards Against Humanity — Chicago, IL": "mfrost@cmrjb.org",
  "Cedar Rapids School District — Cedar Rapids, IA": "aszoke@cmrjb.org",
  "Chartwell @ UW Superior — Superior, WI": "echavez@cmrjb.org",
  "Chartwell @ Xavier University — Cincinnati, OH": "jtyler@cmrjb.org",
  "Chartwells @ Cudahy School District — Cudahy, WI": "jolson@cmrjb.org",
  "Chartwells @ UW La Crosse, WI — La Crosse, WI": "cbiami@cmrjb.org",
  "Chartwells @ UW River Falls — River Falls, WI": "cbiami@cmrjb.org",
  "Chartwells @ Whitewater, WI — Whitewater, WI": "jolson@cmrjb.org",
  "Chicago Family Medical Center — Chicago, IL": "adiaz@cmrjb.org",
  "Cincinnati Sportservice Inc. d/b/a GABP (Vendors) — Cincinnati, OH": "jtyler@cmrjb.org",
  "Cincinnati Sportservice, Inc d/b/a GABP (Concesions) — Cincinnati, OH": "jtyler@cmrjb.org",
  "Cindus Corp. — Cincinnati, OH": "jtyler@cmrjb.org",
  "City of Duluth — Duluth, MN": "echavez@cmrjb.org",
  "Cleveland Sportservice, Inc. (Delaware North at Progressive Fields) — Cleveland, OH": "rwilson@cmrjb.org",
  "Compass @ Detroit Edison Nuclear (Newport + Monroe, M I) — Monroe, MI": "rburks@cmrjb.org",
  "Compass @ Trine University - Bon Appetit — Angola, IN": "dclark@cmrjb.org",
  "Coplas Inc. — Sterling Heights, MI": "cmartin@cmrjb.org",
  "Creative Foam Corporation — Fenton, MI": "rburks@cmrjb.org",
  "Creative Foam Corporation/Composite Systems and Automotive — Fenton, MI": "rburks@cmrjb.org",
  "Curto Ligonier Foundries Company — Melrose Park, IL": "msalgado@cmrjb.org",
  "Custom Plastics — Elk Grove Village, IL": "adiaz@cmrjb.org",
  "DB Rediheat, Inc. dba National Bias Fabric Co. — Cleveland, OH": "rwilson@cmrjb.org",
  "DELAWARE  SPORTS  - MILLER PARK - Vendors — Milwaukee, WI": "ptorres@cmrjb.org",
  "DeMoulin Bros. — Greenville, IL": "emoore@cmrjb.org",
  "Detroit Medical Group - VHS of Michigan — Detroit, MI": "rburks@cmrjb.org",
  "Domestic Linen — Youngstown, OH": "kgillis@cmrjb.org",
  "Domestic Linen Supply & Laundry Co. [Detroit] — Detroit, MI": "dnava@cmrjb.org",
  "Domestic Linen Supply Co. — Chicago, IL": "msalgado@cmrjb.org",
  "Domestic Uniform Rental — Kalamazoo, MI": "dnava@cmrjb.org",
  "Drake Hotel — Chicago, IL": "dnava@cmrjb.org",
  "Economy Linen and Towel Service, Inc. — Dayton, OH": "jtyler@cmrjb.org",
  "ELDorado Cap Company c/o American Needle — Eldorado, IL": "aszoke@cmrjb.org",
  "Elior Collegiate Dining @ UW Oshkosh — Oshkosh, WI": "jolson@cmrjb.org",
  "Elite Airline Linen of Chicago — Franklin Park, IL": "dnava@cmrjb.org",
  "Equality Ohio Education — Columbus, OH": "mfrost@cmrjb.org",
  "Estee Bedding Company — Chicago, IL": "jortiz@cmrjb.org",
  "Eurest @ GE Appliance Park, Unit # 6798 — Louisville, KY": "kleblanc@cmrjb.org",
  "Eurest @ John Deere Engineering — Waterloo, IA": "emoore@cmrjb.org",
  "Eurest @ John Deere Engineering (Waterloo) — Waterloo, IA": "emoore@cmrjb.org",
  "Eurest @ Molson Coors — Milwaukee, WI": "cbiami@cmrjb.org",
  "Eurest @ Thrivent Financial Services — Minneapolis, MN": "echavez@cmrjb.org",
  "Eurest Dining @ British Petroleum - Braidwood — Normal, IL": "msalgado@cmrjb.org",
  "Eurest Dining @ Caterpillar Decatur — Decatur, IL": "emoore@cmrjb.org",
  "Eurest Dining @ Caterpillar General Admin Bldg. — Peoria, IL": "mbaeza@cmrjb.org",
  "Eurest Dining @ Caterpillar Pontiac — Pontiac, IL": "mbaeza@cmrjb.org",
  "Eurest Dining @ Caterpillar Tractor - Main Facility — Peoria, IL": "mbaeza@cmrjb.org",
  "Eurest Dining @ Tate & Lyle Co. — Decatur, IL": "emoore@cmrjb.org",
  "Excelled Sheepskin & Leather Coat — Kewanee, IL": "mbaeza@cmrjb.org",
  "Frontline Group (The)  - USAF — Hebron, CT": "msalgado@cmrjb.org",
  "FullBeauty — Indianapolis, IN": "dclark@cmrjb.org",
  "General Linen Supply — Detroit, MI": "rburks@cmrjb.org",
  "Grecian Delight Foods — Elk Grove Village, IL": "msalgado@cmrjb.org",
  "Grecian Delight Foods, Bakery Div — Elk Grove Village, IL": "msalgado@cmrjb.org",
  "GVS — Findlay, OH": "cmartin@cmrjb.org",
  "Hanover Direct Manufacturing, LLC — La Crosse, WI": "cbiami@cmrjb.org",
  "Health Systems Co-Op (H.S.C.L.) — St. Paul, MN": "echavez@cmrjb.org",
  "Hilton Akron/Fairlawn — Akron, OH": "doug.warren@cmrjb.org",
  "Hilton Chicago — Chicago, IL": "jortiz@cmrjb.org",
  "Hilton Milwaukee — Milwaukee, WI": "cbiami@cmrjb.org",
  "HMS - Host - Cincinnati KY Airport — Hebron, OH": "jtyler@cmrjb.org",
  "Holiday Inn Duluth — Duluth, MN": "echavez@cmrjb.org",
  "Holiday Inn North Canton-Radius Hospitality Management, LLC — North Canton, OH": "kgillis@cmrjb.org",
  "Home Goods Company/HG Merchants — Brownsburg, IN": "jortiz@cmrjb.org",
  "HomeGoods - Lordstown DC — Warren, OH": "kgillis@cmrjb.org",
  "Hoosier Park — Anderson, IN": "dclark@cmrjb.org",
  "Hospital Co-Operative Laundry (HCL Denver) — Denver, CO": "msalgado@cmrjb.org",
  "Host Intl. @ Mitchell Intl. Airport — Milwaukee, WI": "ptorres@cmrjb.org",
  "Hotel Indigo — Cleveland, OH": "rwilson@cmrjb.org",
  "HUBCO INC. — Hutchinson, KS": "aszoke@cmrjb.org",
  "Hyatt Regency Chicago — Chicago, IL": "jortiz@cmrjb.org",
  "Hyatt Regency Cleveland at the Arcade — Cleveland, OH": "mfrost@cmrjb.org",
  "Hyatt Regency Milwaukee, Nobel Investment Group, LLC — Milwaukee, WI": "ptorres@cmrjb.org",
  "Hyatt Regency O'Hare — Rosemont, IL": "dnava@cmrjb.org",
  "Inter-Continental Conference — Cleveland, OH": "mfrost@cmrjb.org",
  "Inter-Continental Suites — Cleveland, OH": "mfrost@cmrjb.org",
  "JACK Thisedown Racino LLC — North Randall, OH": "kgillis@cmrjb.org",
  "Kelley's Warehouse (Evergreen CBA) — Cleveland, OH": "rwilson@cmrjb.org",
  "Kentuckians For The Commonwealth — Lexington, KY": "mfrost@cmrjb.org",
  "Lariat Club — Peoria, IL": "mbaeza@cmrjb.org",
  "Lear Corporation (IMA) — Louisville, KY": "kleblanc@cmrjb.org",
  "Levi Strauss Co. — Hebron, KY": "rwilson@cmrjb.org",
  "Levy Premium Foodservice @ Churchill Downs & Trackside OTB — Louisville, KY": "kleblanc@cmrjb.org",
  "Levy Restaurant @ Great Lakes Science Center — Cleveland, OH": "rwilson@cmrjb.org",
  "Levy Restaurant @ Wisconsin Center District — Milwaukee, WI": "cbiami@cmrjb.org",
  "Macy's Inc. - State Street — Chicago, IL": "msalgado@cmrjb.org",
  "Macy's Logistics and Operations — Minooka, IL": "msalgado@cmrjb.org",
  "Madison Labor Temple — Madison, WI": "jolson@cmrjb.org",
  "Mahoning Valley Scrappers - HWS Baseball VI LLC — Niles, OH": "bforrest@cmrjb.org",
  "Marberry The Cleaning Family — North Aurora, IL": "dnava@cmrjb.org",
  "Mazz Scrap LLC dba City Scrap & Salvage — Akron, OH": "doug.warren@cmrjb.org",
  "Mednik Riverbend LLC — St. Louis, MO": "aszoke@cmrjb.org",
  "Meramec Group Inc. — Sullivan, MO": "kleblanc@cmrjb.org",
  "Metalico Akron, Inc. — Akron, OH": "doug.warren@cmrjb.org",
  "Metropolitan Detroit Area Hospital Services, Inc. — Detroit, MI": "rburks@cmrjb.org",
  "Mickey's Cleanroom — Chicago, IL": "adiaz@cmrjb.org",
  "Mickey's Linen & Towel Chicago — Chicago, IL": "adiaz@cmrjb.org",
  "Mickey's Linen & Towel Villa Pk — Villa Park, IL": "adiaz@cmrjb.org",
  "Mickey's Linen Hammond IN — Hammond, IN": "jortiz@cmrjb.org",
  "Midway Cap Co. — Chicago, IL": "dnava@cmrjb.org",
  "Miss Elaine — St. Louis, MO": "kleblanc@cmrjb.org",
  "MN350 — Minneapolis, MN": "mfrost@cmrjb.org",
  "Monona Catering LLC — Madison, WI": "jolson@cmrjb.org",
  "Monterey Mills, Inc. — Janesville, WI": "jolson@cmrjb.org",
  "NEO LLC (Lake County Captains) — Eastlake, OH": "rwilson@cmrjb.org",
  "NOVO Health Services — Madison, WI": "ptorres@cmrjb.org",
  "NuCentury Textile Services — Toledo, OH": "doug.warren@cmrjb.org",
  "Oak View Group - Ovations Spectra — Cincinnati, OH": "jtyler@cmrjb.org",
  "Ohio Enviromental Council (OEC) — Columbus, OH": "mfrost@cmrjb.org",
  "Ohio Organizing Collabrotive — Youngstown, OH": "mfrost@cmrjb.org",
  "Open Kitchens — Chicago, IL": "adiaz@cmrjb.org",
  "Owens Corning - Summit, IL Roofing Plant - OC Roofing — Summit, IL": "adiaz@cmrjb.org",
  "Oxxford Clothing — Chicago, IL": "msalgado@cmrjb.org",
  "P. J. McIntyres — Cleveland, OH": "rwilson@cmrjb.org",
  "Palmer House Hilton — Chicago, IL": "jortiz@cmrjb.org",
  "Pendleton Woolen Mills — Bellevue, NE": "aszoke@cmrjb.org",
  "Peoples Action Institute — Chicago, IL": "mfrost@cmrjb.org",
  "Pfister Hotel — Milwaukee, WI": "cbiami@cmrjb.org",
  "Policy Matters Ohio — Cleveland, OH": "mfrost@cmrjb.org",
  "Premier Catering, Inc. — Toledo, OH": "doug.warren@cmrjb.org",
  "ProAmpac (Gateway Packaging) — Kansas City, MO": "kleblanc@cmrjb.org",
  "Radisson Hotel/Associated Hotels Duluth, Inc. — Duluth, MN": "echavez@cmrjb.org",
  "Ranier Liquor Store — Ranier, MN": "echavez@cmrjb.org",
  "Reeds Sportwear (Evergreen) — Detroit, MI": "rburks@cmrjb.org",
  "Reef Bar — Duluth, MN": "echavez@cmrjb.org",
  "Ridge Global — West Chester, OH": "jtyler@cmrjb.org",
  "Ritz Carlton Hotel — Chicago, IL": "jortiz@cmrjb.org",
  "Roman Decorating Products — Calumet City, IL": "dnava@cmrjb.org",
  "Roscoe Company — Chicago, IL": "jortiz@cmrjb.org",
  "Royal Lace Div - Mafcote Industries — Louisville, KY": "kleblanc@cmrjb.org",
  "Sage Dining / FLIX Culver Academy — Culver, IN": "dclark@cmrjb.org",
  "Savor - Peoria Civic Center — Peoria, IL": "mbaeza@cmrjb.org",
  "Serta Restokraft — Romulus, MI": "rwilson@cmrjb.org",
  "Six Flags Entertainment - Sawmill Creek Resort — Huron, OH": "doug.warren@cmrjb.org",
  "Skokie Valley Laundry & Cleaners — Highwood, IL": "dnava@cmrjb.org",
  "Sodexo @ GE Electric Evendale — Cincinnati, OH": "jtyler@cmrjb.org",
  "Sodexo @ Ohio Northern University (ONU) Food — Ada, OH": "doug.warren@cmrjb.org",
  "Sodexo @ Ohio Northern University (ONU) Maintenance and Grounds — Ada, OH": "doug.warren@cmrjb.org",
  "Sodexo @ UW Eau Claire — Eau Claire, WI": "cbiami@cmrjb.org",
  "Sparks Hotel Beachwood — Beachwood, OH": "mfrost@cmrjb.org",
  "St. Louis Embroidery — Wentzville, MO": "emoore@cmrjb.org",
  "Stanbury Uniforms — Brookfield, MO": "kleblanc@cmrjb.org",
  "Suncast Corp. — Batavia, IL": "msalgado@cmrjb.org",
  "Superior Trim, Inc. - (September Ends) — Springfield, OH": "cmartin@cmrjb.org",
  "Superior Trim, Inc. - Pieco LLC — Findlay, OH": "cmartin@cmrjb.org",
  "T.J. Maxx — Evansville, IN": "emoore@cmrjb.org",
  "The Great Put On — Flint, MI": "rburks@cmrjb.org",
  "The Madison Concourse Hotel and Governor’s wClub — Madison, WI": "cbiami@cmrjb.org",
  "The Toledo Club — Toledo, OH": "rburks@cmrjb.org",
  "TJX Digital Dayton — Dayton, OH": "bforrest@cmrjb.org",
  "TOPPAN Flexible Packaging (Sonoco) — Edinburgh, IN": "dclark@cmrjb.org",
  "Trustage @ Cuna Mutual — Madison, WI": "jolson@cmrjb.org",
  "Twin City Tanning — South St. Paul, MN": "echavez@cmrjb.org",
  "Union Prescription Center — Mt. Morris, MI": "rburks@cmrjb.org",
  "United Hospital Services — Indianapolis, IN": "mbaeza@cmrjb.org",
  "Vestis @ Chicago - MC 701 — Chicago, IL": "adiaz@cmrjb.org",
  "Vestis @ Cincinnati - MC 543 — Cincinnati, OH": "jtyler@cmrjb.org",
  "Vestis @ Dayton  MC 322 — Dayton, OH": "jtyler@cmrjb.org",
  "Vestis @ Des Moines - MC 637 — Des Moines, IA": "emoore@cmrjb.org",
  "Vestis @ Fulton, MO — Fulton, MO": "aszoke@cmrjb.org",
  "Vestis @ Madison - MC 614 — Madison, WI": "ptorres@cmrjb.org",
  "Vestis @ MC 544 ( Production) — Toledo, OH": "doug.warren@cmrjb.org",
  "Vestis @ Sikeston, MO — Sikeston, MO": "kleblanc@cmrjb.org",
  "Vestis @ Springfield, MO — Springfield, MO": "kleblanc@cmrjb.org",
  "Vestis @ St. Louis, MO - MC 617 — St. Louis, MO": "emoore@cmrjb.org",
  "Vestis Cleanroom @ AmeriPride Linen & Apparel Services — Minneapolis, MN": "echavez@cmrjb.org",
  "Vestis Services, LLC @ MC 544  (Drivers) — Toledo, OH": "doug.warren@cmrjb.org",
  "Volume Service @  Centerplate Indianapolis Convention Center — Indianapolis, IN": "dclark@cmrjb.org",
  "West Michigan Shared Hospital Laundry — Grand Rapids, MI": "dnava@cmrjb.org",
  "Westin Cleveland Downtown — Cleveland, OH": "mfrost@cmrjb.org",
  "Westin Hotel Cincinnati — Cincinnati, OH": "jtyler@cmrjb.org",
  "Westminster Village, Inc. — Bloomington, IL": "mbaeza@cmrjb.org",
  "Whitsons — Berkeley, IL": "adiaz@cmrjb.org",
  "Wilson Sporting Goods Company — Ada, OH": "doug.warren@cmrjb.org",
  "Wiman Corporation — Sauk Rapids, MN": "echavez@cmrjb.org",
  "Xerox Corp - Middletown OH — Middletown, OH": "doug.warren@cmrjb.org",
  "Beloit College — Beloit, WI": "ptorres@cmrjb.org",
  "Six Flags — Sawmill Creek Resort": "doug.warren@cmrjb.org"
};
